### ISSUE TITLE
Table not spawnned in Gazebo world

### ISSUE THREAD

**Issue by predator4hack** [JdeRobot/IndustrialRobots#14]
`roslaunch ur5_gripper_demo initialize.launch` does not spawns table in the Gazebo world. 

These are the set of warnings that was shown:
`Deprecated: xacro tag 'property' w/o 'xacro:' xml namespace prefix (will be forbidden in Noetic)`
`The complete state of the robot is not yet known.  Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8`

**Comment by sixer51** [comment]
Did you solve this problem with the solution in https://github.com/JdeRobot/RoboticsAcademy/issues/802?

**Comment by predator4hack** [comment]
Yes, the update solved this problem
