### ISSUE TITLE
Issues in loading ur5 group

### ISSUE THREAD

**Issue by predator4hack** [JdeRobot/IndustrialRobots#16]
When trying to simulate pick_place using `rosrun ur5_gripper_demo ur5_pick_and_place.py` gives throws error : 
`Group 'ur5' was not found` This is probably because of mismatch in names of group in ur5.srdf and ur5_pick_and_place.py

**Comment by sixer51** [comment]
solved in #17 
Thanks for solving this problem @predator4hack
